# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-added-large-files" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.7"
hooks = [
  {
    id = "ruff-check",
    args = ["--fix"]
  },
  { id = "ruff-format" }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "pyrefly",
    name = "pyrefly",
    entry = "uv run pyrefly check",
    language = "system",
    types_or = [
      "python",
      "pyi"
    ],
    pass_filenames = false
  }
]
